In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a + 4 #adds 4 to each elements of the matrix

array([5, 6, 7])

In [5]:
a * 5 #multiplication of 5 to each elements

array([ 5, 10, 15])

In [18]:
b = np.array([[1,2],[4,5]])

In [19]:
c = np.array([[4,5],[7,8]])

In [20]:
b

array([[1, 2],
       [4, 5]])

In [21]:
c

array([[4, 5],
       [7, 8]])

In [22]:
b.dot(c) #matrix multiplication

array([[18, 21],
       [51, 60]])

In [27]:
b.reshape(2,2) #matrix reshape

array([[1, 2],
       [4, 5]])

In [28]:
#indexing

In [29]:
d = np.arange(20)

In [30]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
d[0:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
e = np.arange(25).reshape(5,5)

In [34]:
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
e[0:2,0:5]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
e[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])