In [2]:
import numpy as np

In [3]:
mat = [[1,2,3],[4,5,6]] #create matrix 

In [4]:
np_mat = np.array(mat)

In [5]:
np_mat

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(mat)

list

In [7]:
type(np_mat) #to check type of array

numpy.ndarray

In [8]:
#create zeroes matrix

In [9]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [10]:
#create ones matrix

In [11]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [12]:
#create identity matrix ie., diagonals are one

In [13]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
#create random matrix

In [15]:
np.random.randn(3,5)

array([[-1.87275282,  0.32818857, -1.82317802, -0.78357862, -1.40096727],
       [ 0.22089215, -1.35097412,  0.34032324,  1.28356303,  0.4595456 ],
       [ 0.96784861,  0.30473849,  0.72950882,  0.20380342,  1.22071576]])

In [16]:
#create random matrix with integers

In [21]:
np.random.randint(2)

0